# Site settings
title: YMC - Web Developer
description: "YMC 기술블로그"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://ymc-crow.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: YMC의 기술블로그
user_title: YMC의 기술블로그
email: ymch65@gmail.com
twitter_username: 
github_username:  ymc-crow
gplus_username:  
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: ymc-crow
profile_picture: /assets/img/me.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: about me
      url: /about
      key_trigger: 2
    - title: all posts
      url: /posts
      key_trigger: 3
  section_2:
    - title: javascript
      url: /javascript
      key_trigger: js
    - title: html_css
      url: /html_css
      key_trigger: fe  
    - title: python
      url: /python
      key_trigger: py
    - title: pe-기술사문제
      url: /pro_engineer
      key_trigger: pe
    - title: interview
      url: /interview
      key_trigger: iv

# projects in header index
projects:
  - name: jekyll + github로 기술블로그 만들기
    url: https://github.com/ymc-crow/ymc-crow.github.io


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
